import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar/page";
import Transition from "./components/Transition/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Transition>{children}</Transition>
      </body>
    </html>
  );
}
